-- Cleanup Legacy Recurring Event Instances
-- 
-- This migration removes old recurring event instances that were created
-- by the legacy system before RRULE migration. These are duplicate child
-- instances that are no longer needed since FullCalendar now expands
-- RRULE events automatically.
--
-- Safe to delete: Events with recurringGroupId but WITHOUT rrule
-- (these are child instances from the old system)
--
-- Keep: Events with rrule (parent events) or without recurringGroupId

-- First, let's log what we're about to delete for safety
DO $$
DECLARE
  delete_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO delete_count
  FROM public.calendar_events
  WHERE recurring_group_id IS NOT NULL 
    AND rrule IS NULL;
  
  RAISE NOTICE 'Found % legacy recurring event instances to delete', delete_count;
END $$;

-- Delete legacy recurring event instances
-- These are the individual occurrences that were generated by the old system
-- Now that we have RRULE, FullCalendar will generate occurrences on-the-fly
DELETE FROM public.calendar_events
WHERE recurring_group_id IS NOT NULL 
  AND rrule IS NULL;

-- Log completion
DO $$
BEGIN
  RAISE NOTICE 'Legacy recurring instances cleanup complete';
  RAISE NOTICE 'Remaining events should only be:';
  RAISE NOTICE '  - Events with rrule (parent recurring events)';
  RAISE NOTICE '  - Events without recurring_group_id (non-recurring events)';
END $$;
